DjangoTrain/DjangoTrain/urls.py
from django.contrib import admin
from django.urls import include, re_path
from django.conf.urls import handler404, handler500
from . import views

handler404 = 'DjangoTrain.views.handler404'
handler500 = 'DjangoTrain.views.handler500'

app_name='DjangoTrain'

urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^contact/$', views.contact, name='contact'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^blog/', include('blog.urls'))
]

DjangoTrain/blog/urls.py
from . import views
from django.urls import include, re_path

app_name='blog'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^articles/(?P<id>[0-9]+)$', views.show, name='show'),
]

DjangoTrain/blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()

DjangoTrain/DjangoTrain/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'pages/about.html')


def contact(request):
    return render(request, 'pages/contact.html')

def handler404(request, exception):
    return render(request, 'errors/404.html', {'error': exception}, status=404)

def handler500(request):
    return render(request, 'errors/500.html', {}, status=500)

DjangoTrain/blog/views.py
from django.shortcuts import render
from .Article import Article

def index(request):    
    articles = Article.all()
    return render(request, 'index.html', {'articles': articles})

def show(request, id):
    article = Article.findById(id)
    return render(request, 'show.html', {'article': article})

DjangoTrain/blog/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog</title>
</head>

<body>
    <h1>Blog home</h1>

    {% for article in articles %}

    <article>
        <h2><a href="{% url 'blog:show' id=article.id %}">#{{ article.id }} - {{ article.title|upper }}</a></h2>
        <p> {{ article.body|truncatewords:3 }}</p>

        <p><a href="{% url 'blog:show' id=article.id %}">Lire la suite</a></p>
    </article>


    {% empty %}
    <p>List empty</p>
    {% endfor %}
</body>

</html>

DjangoTrain/blog/templates/show.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Details</title>
</head>

<body>
    <h1># {{ article.id }} - {{ article.title }}</h1>
    <p>{{ article.body }}</p>
</body>

</html>

DjangoTrain/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
</head>
<body>
    <h1>Home</h1>
</body>
</html>

DjangoTrain/templates/pages/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contact</title>
</head>
<body>
    <h1>Contact</h1>
</body>
</html>